# .goreleaser.yml
# Build customization
version: 2

project_name: helm-gcs

builds:
  - id: helm-gcs
    main: ./cmd/helm-gcs/main.go
    binary: helm-gcs
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/MarcoRezkallah/helm-gcs/cmd/helm-gcs/cmd.version={{.Version}} -X github.com/MarcoRezkallah/helm-gcs/cmd/helm-gcs/cmd.commit={{.Commit}} -X github.com/MarcoRezkallah/helm-gcs/cmd/helm-gcs/cmd.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    # Skip windows arm64 until toolchain confirmed
    ignores:
      - goos: windows
        goarch: arm64

archives:
  - id: helm-gcs
    builds:
      - helm-gcs
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{- if eq .Os \"darwin\" -}}Darwin{{- else if eq .Os \"linux\" -}}Linux{{- else -}}{{ .Os }}{{- end -}}_{{- if eq .Arch \"amd64\" -}}x86_64{{- else -}}{{ .Arch }}{{- end -}}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: git